services:
  waoflix_app:
    image: waoflix/python
    build:
      context: ./
      dockerfile: ./Dockerfile

    restart: always
    ports:
      - 0.0.0.0:$PORT:8000
    container_name: waoflix_app_container