services:
  waoflix_app:
    image: waoflix/python
    build:
      context: ./
      dockerfile: ./Dockerfile

    restart: always
    # ports:
    #   - 0.0.0.0:$PORT:8000
    container_name: waoflix_app_container

    volumes:
      - static:/static

    environment:
      - ALLOWED_HOSTS=waoflixapp
      - SECRET_KEY=${SECRETKEY:-"django-insecure-^=6$ihinp^5x95iku!j@xcc*^u0wa37f%y7*xbpjpgurpqg&du"}



  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile

    volumes:
      - static:/static

    ports:
      - 0.0.0.0:$PORT:80

    depends_on:
      - waoflix_app




volumes:
  static: