services:
  custom_wpn_app:
    image: custom_wpn/python
    build:
      context: ./
      dockerfile: ./Dockerfile

    volumes:
      - static:/static

    restart: always
    # ports:
    # - 0.0.0.0:8000:8000

    container_name: custom_wpn_container

    environment:
      - DEBUG_MODE
      - ALLOWED_HOSTS
      - SECRET_KEY
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_HOST_USER
      - SMTP_HOST_PASSWORD
      - LMS_APIKEY
      - CSRF_TRUSTED_ORIGINS

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile

    volumes:
      - static:/static

    ports:
      - 0.0.0.0:$PORT:80

    depends_on:
      - custom_wpn_app

volumes:
  static:
