# Generated by Django 2.2.12 on 2023-01-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WDJApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdjcomments',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wdjcontact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wdjlogin',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wdjmovies',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wdjusers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
