# Generated by Django 2.2.12 on 2023-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WDJComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('comMail', models.CharField(max_length=100)),
                ('comReason', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WDJContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('conMail', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('conReason', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WDJLogin',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=25)),
                ('sess_uuid', models.TextField()),
                ('passWord', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WDJMovies',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=300)),
                ('poster_url', models.CharField(max_length=300)),
                ('movie_title', models.CharField(max_length=300)),
                ('movieRating', models.CharField(max_length=5)),
                ('movieQuality', models.CharField(max_length=10)),
                ('movieFileSize', models.CharField(max_length=10)),
                ('movieLanguage', models.CharField(max_length=20)),
                ('movieReleaseDate', models.CharField(max_length=20)),
                ('movieStory', models.TextField()),
                ('movieDownloadURL', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WDJUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid_md5', models.TextField()),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=75)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
