# Generated by Django 2.2.12 on 2023-01-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WDJApp', '0002_auto_20230108_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDJTempMail',
            fields=[
                ('mail_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('ip_addr', models.GenericIPAddressField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WDJTempMailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.TextField()),
                ('mail_html', models.TextField()),
                ('mail_subject', models.TextField()),
                ('message_id', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('msgDownUrl', models.CharField(max_length=255)),
                ('temp_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WDJApp.WDJTempMail')),
            ],
        ),
    ]
