# Generated by Django 4.1.5 on 2023-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WDJApp', '0005_wdjtempmailcontent_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdjtempmail',
            name='domain',
            field=models.CharField(default='example.com', max_length=255),
        ),
    ]
