# Generated by Django 4.1.5 on 2023-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WDJApp', '0006_wdjtempmail_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdjtempmail',
            name='ip_addr',
            field=models.GenericIPAddressField(default='192.168.1.1'),
        ),
    ]
